### ISSUE TITLE
Why composer in production images?

### ISSUE THREAD

**Issue by jorge07** [1ma/dockertronics#1]
When do you need to run composer commands on production?

**Comment by jorge07** [comment]
also git...

**Comment by 1ma** [comment]
You don't need it at runtime but it comes in quite handy when building the Dockerfile. At this point I'm willing to trade some image size for that convenience.

Unfortunately `git` is mandatory as soon as you have `composer`, since that is what it'll use as a fallback when an archive file of one of your dependencies is not available (for instance when using a direct link to the package repository, or when pegging to a specific commit).

**Comment by jorge07** [comment]
The production container should be only for this proposal, production. With minimun binaries as possible, min vulnerabilities, min maintenance... If you are building the artifact then, it is a **build** tag instead the base.

**Comment by jorge07** [comment]
Think on that workflow please:

Given a **dev** container to compile the project
When I extract the compiled artifact with _docker cp_
Then I add it on the production container using Dockerfile instruction **COPY**
And I warm the cache

**Comment by 1ma** [comment]
Yes, your principles are sound, and that's how I've been building deployable images until now, too. However, as I said, at this point I'm willing to trade off some image size and "rigorousness" in order to simplify these steps.

On this specific case I fail to see how adding git & composer can lead to potential vulnerabilities. These are just local binaries, not daemons exposing extra ports to the outside world nor anything like that. Prove me wrong, though, and I'll wipe 'em :P

**Comment by jorge07** [comment]
If you have git installed, you may have a user with good permissions, if someone penetrate on your server, can access to your repository too... Its just an example, but take care of that. I still dont see your point, but you may have your reasons...
